name: Build and run tests
on: [push]
jobs:
  build:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-2019, macos-11]

    steps:
      - uses: actions/checkout@v2

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.1.2
        env:
          CIBW_ARCHS: auto64

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
  run:
    name: Run tests on ${{ matrix.os }}
    needs: [build]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-2019-gcc, macos-11]

    steps:
      - uses: actions/checkout@v2

      - name: Clean source code
        run: rm -r ./libmir

      - uses: actions/download-artifact@v2
        with:
          name: artifact
          path: built_wheels

      - name: Install packages
        run: python3 -m pip install --no-index --find-links=./built_wheels libmir
      
      - name: Run tests
        run: python3 run_tests.py
